class Autogenerated {
  int? statusCode;
  String? message;
  List<Data>? data;
  int? resultCount;

  Autogenerated({this.statusCode, this.message, this.data, this.resultCount});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode'];
    message = json['message'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    resultCount = json['resultCount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['statusCode'] = this.statusCode;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['resultCount'] = this.resultCount;
    return data;
  }
}

class Data {
  int? productID;
  String? productName;
  String? description;
  String? category;
  String? subCategory;
  String? uom;
  double? price;
  String? weight;
  String? size;
  int? productRank;
  String? productImage;
  String? brand;
  String? productCode;
  bool? disclosePrice;
  String? alterPriceText;
  double? pointsToEarn;

  Data(
      {this.productID,
        this.productName,
        this.description,
        this.category,
        this.subCategory,
        this.uom,
        this.price,
        this.weight,
        this.size,
        this.productRank,
        this.productImage,
        this.brand,
        this.productCode,
        this.disclosePrice,
        this.alterPriceText,
        this.pointsToEarn});

  Data.fromJson(Map<String, dynamic> json) {
    productID = json['product_iD'];
    productName = json['product_name'];
    description = json['description'];
    category = json['category'];
    subCategory = json['sub_Category'];
    uom = json['uom'];
    price = json['price'];
    weight = json['weight'];
    size = json['size'];
    productRank = json['product_rank'];
    productImage = json['product_image'];
    brand = json['brand'];
    productCode = json['product_code'];
    disclosePrice = json['disclose_price'];
    alterPriceText = json['alter_price_text'];
    pointsToEarn = json['points_to_earn'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['product_iD'] = this.productID;
    data['product_name'] = this.productName;
    data['description'] = this.description;
    data['category'] = this.category;
    data['sub_Category'] = this.subCategory;
    data['uom'] = this.uom;
    data['price'] = this.price;
    data['weight'] = this.weight;
    data['size'] = this.size;
    data['product_rank'] = this.productRank;
    data['product_image'] = this.productImage;
    data['brand'] = this.brand;
    data['product_code'] = this.productCode;
    data['disclose_price'] = this.disclosePrice;
    data['alter_price_text'] = this.alterPriceText;
    data['points_to_earn'] = this.pointsToEarn;
    return data;
  }
}