import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:task/Screens/profile_screen.dart';
import 'package:http/http.dart' as http;
import '../DataClassModels/productdatamodel.dart';
import 'login_screen.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);


  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {

  late Future prod_det;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    prod_det = fetchProductData();
  }

  ///Product api call
  Future fetchProductData() async{
    final response = await http.post(Uri.parse(product_url),
        body: {"PageNo":1.toString(),"PageSize":10.toString()},
        headers: {
          'Authorization': 'Bearer $u_token'
        }
    );
    if(response.statusCode == 200){
      Autogenerated list =  Autogenerated.fromJson(jsonDecode(response.body));

      String? temp = list.data?.length.toString();

      for(var i=0; i< int.parse(temp!);i++){
        p_det.add(
          Product(p_name: list.data![i].productName, p_image:list.data![i].productImage,p_points:list.data![i].pointsToEarn.toString()),
        );
        // For knowing whether the data is loading or not : print(p_det.length);
      }
      // for test use : print("success");
    }else{
      throw Exception('Failed to load album');
    }

  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      drawer: Drawer(),
      appBar: AppBar(
        backgroundColor: Colors.white,
        iconTheme: IconThemeData(color: Colors.black),
        centerTitle: true,
        title: Text("Dashboard",style: TextStyle(color: Colors.black),),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 8),
            child: Icon(Icons.notifications_none,size: 30,),
          ),
        ],
      ),

      body: SingleChildScrollView(
        child: Column(

          children: [
            //Profile Card
            GestureDetector(
              onTap: (){
                Navigator.push(context, MaterialPageRoute(builder: (context) => ProfileScreen()),);
              },
              child: Padding(
                padding: const EdgeInsets.fromLTRB(8,8,8,2),
                child: Card(
                  elevation: 4,
                  color: Color(0xFFF5CC00),
                  child: Column(
                    children: [
                      //
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              Padding(
                                padding: const EdgeInsets.only(right: 8),
                                child: SizedBox(
                                    height:65,
                                    width:65,
                                    child: Image.asset('assets/img_1.png')),
                              ),

                              Padding(
                                padding: const EdgeInsets.only(left: 10),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(u_name,style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 17,
                                        fontWeight: FontWeight.bold
                                    ),),
                                    Padding(
                                      padding: const EdgeInsets.only(top: 2),
                                      child: Text(u_email,style: TextStyle(
                                        fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: 13
                                      ),),
                                    )
                                  ],
                                ),
                              ),
                            ],
                          ),

                          Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: SizedBox(
                                height:45,
                                width:45,
                                child: Image.asset('assets/flutter.png')),
                          ),

                        ],
                      ),
                      //
                      SizedBox(height: 18,),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Column(
                            children: [
                              Text("YOUR POINT BALANCE",style: TextStyle(
                                color: Colors.white,
                                fontWeight: FontWeight.bold,
                                fontSize: 14
                              ),),


                              Padding(
                                padding: const EdgeInsets.only(top: 10),
                                child: Text(u_available,style: TextStyle(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 24
                                ),),
                              ),
                            ],
                          ),
                        ],
                      ),
                      //

                      SizedBox(
                        height: 8,
                      ),
                      Padding(
                        padding: const EdgeInsets.only(bottom: 3),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                          children: [
                            CommonPointCol("POINT EARNED",u_earned),
                            CommonPointCol("POINT EXPIRING",u_expiring),
                            CommonPointCol("POINT REDEEMED",u_redeemed),
                          ],
                        ),
                      ),
                    ],
                  ),

                ),
              ),
            ),

            //Divider
            Padding(
              padding: const EdgeInsets.only(left: 5,right: 5,bottom:35),
              child: Column(
                children: [
                  Container(
                    color: Colors.black26,
                    height: 2,
                  ),
                  Container(
                    decoration: BoxDecoration(
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black12,
                          blurRadius: 1.0,
                          spreadRadius: 0.0,
                          offset: Offset(1.0, 1.0), // shadow direction: bottom right
                        )
                      ],
                    ),
                    height: 2,
                  ),
                ],
              ),
            ),


            //GridView
            FutureBuilder(
                future: prod_det,
                builder:(context,snapshot){
                  return  Padding(
                    padding: const EdgeInsets.fromLTRB(20,10,20,10),
                    child: GridView.count(
                      childAspectRatio: 1/1.4,
                      crossAxisCount: 2,
                      shrinkWrap: true,
                      physics: ScrollPhysics(),
                      children: List.generate(p_det.length, (index){
                        return Container(
                          child: Padding(
                            padding: const EdgeInsets.only(left:3,right:3,bottom: 5),
                            child: Stack(
                              alignment: Alignment.topCenter,
                              children: [
                                Padding(
                                  padding: const EdgeInsets.only(top:9),
                                  child: Card(
                                    elevation: 4,
                                    color: Colors.grey[350],
                                    child: Padding(
                                      padding: const EdgeInsets.only(top:25,left:25,right:25),
                                      child: Column(
                                        children: [
                                          Container(
                                              width:90,
                                              height:135,
                                              child: Image.network(
                                                p_det[index].p_image.toString(),
                                                fit: BoxFit.fill,
                                                errorBuilder: (context,error, stackTrace){
                                                  return Image.asset('assets/flutter.png');
                                                },
                                              )
                                          ),
                                          Padding(
                                            padding: const EdgeInsets.only(top:10),
                                            child: SizedBox(
                                              height:40,
                                              width:125,
                                              child: Text(p_det[index].p_name.toString(),style: TextStyle(
                                                fontSize:12,
                                              ),
                                                textAlign: TextAlign.center,
                                              ),
                                            ),
                                          )
                                        ],
                                      ),
                                    ),
                                  ),
                                ),

                                Card(
                                  color: Colors.amber,
                                  child: Padding(
                                    padding: const EdgeInsets.fromLTRB(10,3,10,3),
                                    child: Text("Earn "+ p_det[index].p_points.toString().split('.')[0]+" Points",style: TextStyle(fontSize: 12),),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        );
                      }),
                    ),
                  );
                }
            ),
          ],
        ),
      ),
    );
  }
}

//CommonProfileCardColumn
Widget CommonPointCol(String p_name,String p_num ){

  return SizedBox(
    height: 40,
    width: 95,
    child: Column(
      children: [
        Text(p_name,style: TextStyle(
            color: Colors.white,
            fontSize: 11,
            fontWeight: FontWeight.bold
        ),),
        Padding(
          padding: const EdgeInsets.only(top: 6),
          child: Text(p_num,style: TextStyle(
              color: Colors.white,
              fontSize: 16,
              fontWeight: FontWeight.bold
          ),),
        )
      ],
    ),
  );
}